Region: ap-northeast-2
Image:
  Os: alinux2
  CustomAmi: ami-0b1bee5107aafda8d
SharedStorage:
    # install your shared applications in /apps, it can be archived through
    # a snapshot that you can reuse with other clusters.
  - Name: SharedEBS
    StorageType: Ebs
    MountDir: /apps
    EbsSettings:
      VolumeType: gp3
      Size: 200
      Throughput: 300
      Iops: 6000
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 4800
      DeploymentType: PERSISTENT_1
      PerUnitStorageThroughput: 200
      DataCompressionType: LZ4
      ImportPath: ${DataBucketURI}
HeadNode:
  InstanceType: m5.2xlarge
  Networking:
    SubnetId: subnet-0e0c094181fbcdc6c
  Ssh:
    KeyName: lab-your-key
  LocalStorage:
    RootVolume:
      Size: 100

Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: compute
    ComputeSettings:
        LocalStorage:
          # NVMe drives will be set in RAID0
          EphemeralVolume:
            MountDir: /local_scratch
          # This is your root volume
          RootVolume:
            Size: 200
    ComputeResources:
    - Name: p4d24xlarge
      InstanceType: p4d.24xlarge
      MinCount: 0
      MaxCount: 4
      Efa:
        Enabled: true
    Iam:
      S3Access:
        - BucketName: ${DataBucket}
    Networking:
      PlacementGroup:
        Enabled: true
      SubnetIds:
      - subnet-042b3a1b3b317b633
